[platformio]
# Cau hinh duong dan ma nguon la thu muc hien tai
src_dir = .
include_dir = .

[env:uno]
platform = atmelavr
board = uno
framework = arduino

# Su dung cac thu vien da co trong thu muc Arduino libraries cua ban
lib_extra_dirs = 
    /home/ddd/Arduino/libraries
