[platformio]
# Cau hinh duong dan ma nguon la thu muc chua file .ino chinh
src_dir = SmartCar_Core_20210127
include_dir = SmartCar_Core_20210127

[env:uno]
platform = atmelavr
board = uno
framework = arduino

# Su dung cac thu vien da co trong thu muc Arduino libraries cua ban
lib_extra_dirs = 
    /home/ddd/Arduino/libraries

# Cau hinh thu vien can thiet
lib_deps =
    IRremote

# Tu dong tim cong COM khi upload
upload_speed = 115200
monitor_speed = 9600
